### ISSUE TITLE
Question about the rev1/ndsimslv/ testbench

### ISSUE THREAD

**Issue by liuzixuan1212** [chipsalliance/aib-phy-hardware#34]
Hi,

I have some question about the testbench in rev1/ndsimslv/ folder. 
The first question is how to modify the testbench to let the fpga aib module(slave) sends data and the master aib module receive data and loopback to the fpga aib module side? 
The second question is how to cancel the alignment mode. whether it need to change the configuration bits both in the master aib side and slave(fpga) aib side, and in that case how to change the configuration bits.  

Sincerely
Zixuan Liu

**Comment by dkehlet** [comment]
1st question: This can be done; it just needs to be developed.  Can you be more specific please?
2nd question: You should review all the examples.  Also refer to the open_source_aib_csr.xlsx in the docs folder.

**Comment by dkehlet** [comment]
Will close in a week if there is no further discussion.
