### ISSUE TITLE
v2 slave (follower) CSR differences

### ISSUE THREAD

**Issue by dkehlet** [chipsalliance/aib-phy-hardware#36]
The v2_slave configuration is slightly different than the master.

cfg_avmm_write addresses are "h2xx"

h208 rx fifo
Bit 27: 0 fifo single width, 1 fifo double width
Bit 0: 0 no swap, 1 rxswap
    
h210 rx fifo
Bits 2:1: 00 FIFO 1x, 01 FIFO 2x, 11 Register
Bit 0:  0 word alignment disable, for FIFO 1x mode, 1 word alignment enable, for FIFO 2x mode

h218 tx fifo
Bit 23: 0 disable word marking, 1 enable word marking
Bits 22:21: 00 FIFO 1x, 01 FIFO 2x, 11 Register mode
Bit 0: 0 no swap, 1 swap data from MAC to far side

Examples:
2x FIFO Mode
208	0A780204
210	02871F03
218	47A08004

Register mode
208	02780204
210	02871f06
218	47608004

**Comment by weizhuintel** [comment]
Yes. V2 slave register definition is not the same as the master.

**Comment by dkehlet** [comment]
Add a tab to the open_source_aib_csr.xlsx spreadsheet in the docs folder, and put the follower differences there.

**Comment by weizhuintel** [comment]
Added to the spreadsheet. File sent to Julie. Julie will pull the file in.
