### ISSUE TITLE
synthesis of the aib

### ISSUE THREAD

**Issue by liuzixuan1212** [chipsalliance/aib-phy-hardware#4]
Hi

I want to use this interface in my new project. Does this RTL code have been synthesis before. If it has been synthesis, can you tell me about your synthesis environment and how it is synthesis.

Thanks Zixuan

**Comment by rahulrvm82** [comment]
> Hi
> 
> I want to use this interface in my new project. Does this RTL code have been synthesis before. If it has been synthesis, can you tell me about your synthesis environment and how it is synthesis.
> 
> Thanks Zixuan

Hello Zixuan,

I am also planning to use the same for my project.
I want to explore the constraint for this design if implemented .  
If you have any update please ping me.

Thanks 

Rahul

**Comment by dkehlet** [comment]
aib-phy-hardware/rev2/rtl/v2_master and aib-phy-hardware/rev2/rtl/v2_common have been synthesized before, with the important exception: v2_common/ana are macrocells that were built using a custom methodology.
We don't have synthesis support yet but hope to add this in the future.

Dave

**Comment by rahulrvm82** [comment]
Thanks For your response.

Can we have macro.vh file in data base?

This Error has stopped me: Invalid Macro 'AIBADAPTWRAPTCB_SCAN_CHAINS_NUM


Thanks 
Rahul

**Comment by dkehlet** [comment]
Hi Rahul, please look in 
    aib-phy-hardware/rev2/rtl/v1_master/c3dfx/rtl/defines/c3dfx.vh
if you are using the rev1 files, or
    aib-phy-hardware/rev2/rtl/v2_common/c3dfx/rtl/defines/c3dfx.vh
if you are using the rev2 files.

Dave

$ ls
docs/  LICENSE*  README.txt*  rev1/  rev2/
$ grep -r "define AIBADAPTWRAPTCB_SCAN_CHAINS_NUM" .
./rev2/rtl/v1_master/c3dfx/rtl/defines/c3dfx.vh:`define AIBADAPTWRAPTCB_SCAN_CHAINS_NUM 17
./rev2/rtl/v2_common/c3dfx/rtl/defines/c3dfx.vh:`define AIBADAPTWRAPTCB_SCAN_CHAINS_NUM 17
$

**Comment by liuzixuan1212** [comment]
Thanks for your response 

I am now looking for building a AIB model without using dcc and dll. I tried many methods but still can not pass the provided  testbench.  Can you give me some clue about how to remove the dcc and dll module in the AIB design.

Sincerely
Zixuan Liu

**Comment by xinyang2k** [comment]
if you look under rev1/rtl, there is a rtl model that have dummy dcc and dll module which is not doing anything relates to that. You can reference from there. You can use that model directly.

**Comment by dkehlet** [comment]
Please see the README.md in rev2/constraints, just added.
