### ISSUE TITLE
Tristate behavior of aibcr3_analog.v 

### ISSUE THREAD

**Issue by rbaracka** [chipsalliance/aib-phy-hardware#41]
The aibcr3_analog.v model (open source version “v2” ) does not tristate (itx_en_buf=1’b0) unless the drive strength inputs are also zeros (indrv_buf[1:0]=2’b00 and ipdrv_buf[1:0]=2’b00).

**Comment by dkehlet** [comment]
rbaracka found a legitimate issue and it behaves as described. The change in behavior between v1 and v2 in this regard was not intended, but should not cause a problem. I recommend users adopt the current v2 behavior and usage.

Thanks for finding and reporting this issue!
