### ISSUE TITLE
mismatch between code and spec in data calibration

### ISSUE THREAD

**Issue by khanhpvn** [chipsalliance/aib-phy-hardware#43]
Hi,
In the spec, Figure 42, it shows
![image](https://user-images.githubusercontent.com/69887537/90849859-7b38a500-e39a-11ea-90ad-ce5693e55e89.png)
However, in the code, the implement in file rtl/aib_sm.v  line 510 is difference.
![image](https://user-images.githubusercontent.com/69887537/90849896-8ee40b80-e39a-11ea-9244-bea65c0a1042.png)
It should change to "&" instead of "|".

Please help to fix.
Thanks

**Comment by dkehlet** [comment]
Nice find!  Will fix.

**Comment by weizhuintel** [comment]
New rtl uploaded to fix this issue.
