### ISSUE TITLE
Repair of TX0 pin has issue due to wrong connection

### ISSUE THREAD

**Issue by khanhpvn** [chipsalliance/aib-phy-hardware#44]
Hi,
When we test repair with below setting
Set: 	- Mission mode: TX/RX
		- Repair code: 4
		- Repair upper: 0 (lower, TX)
We got the issue that TX0 pin could NOT shift down to ns_rcv_clk pin while TX1 pin could shift down to ns_rcv_clkb pin.
The cause is that idata_iopad is sync to ilaunch_clk so it should connect to tx_ilaunch_clk instead of ns_rcv_clk_frmac
Fix suggestion:
in rtl/aib_ioring.v line 1117, 1118, it should change from ns_rcv_clk_frmac to tx_launch_clk as below.
![image](https://user-images.githubusercontent.com/69887537/90850856-192d6f00-e39d-11ea-9bd8-fbf882185edd.png)

Regards

**Comment by dkehlet** [comment]
Hi Julie, will you evaluate?

**Comment by weizhuintel** [comment]
Clock connection corrected. Link to pull request #46 
--- Wei
