### ISSUE TITLE
open_source_aib_csr.xlsx, v2_slave tab needs example updates

### ISSUE THREAD

**Issue by dkehlet** [chipsalliance/aib-phy-hardware#49]
2x FIFO example: Address 218 should be assigned value 67A08004
Register mode example: Address 218 should be assigned value 67608004
We discovered a FIFO timing problem with the example values listed.

The function of this upper byte is not documented.

**Comment by xinyang2k** [comment]
Updated spread sheet for both master and slave.

**Comment by dkehlet** [comment]
The "usr_csr" tab for master and the v2_slave tab were updated for register at address 218, bits 31:29:

3'b110:  6 read cycle delay
3'b101: 5 read cycle delay
3'b100: 4 read cycle delay
3'b011: 3 read cycle delay
3'b010: 2 read cycle delay

The example in v2_slave was updated for 2x FIFO:
Address 218: 67A08004


67A08004
--




Address | Data
-- | --
218 | 67A08004


Examples | Address | Data
-- | -- | --
2x FIFO Mode | 218 | 67A08004


Examples | Address | Data
-- | -- | --
2x FIFO Mode | 218 | 67A08004


Examples | Address | Data
-- | -- | --
2x FIFO Mode | 218 | 67A08004
