### ISSUE TITLE
Update DBI bit locations in the 2.0 model

### ISSUE THREAD

**Issue by dkehlet** [chipsalliance/aib-phy-hardware#57]
The April update of the AIB 2.0 spec clarified the DBI bit positions in a full rate word. For DBI to show up at DDR Tx[39] and TX[19], the DBI bits occupy full_rate_data_in[79], full_rate_data_in[78], full_rate_data_in[39], full_rate_data_in[38].
Please update the 2.0 model to use these full rate and DDR bit positions.

**Comment by dkehlet** [comment]
[dbi_location_spec_update.pdf](https://github.com/chipsalliance/aib-phy-hardware/files/6593106/dbi_location_spec_update.pdf)

**Comment by xinyang2k** [comment]
Checked in the updated DBI change.
