### ISSUE TITLE
AIB2.0 model doesnt support the receiver-domain transmit clock feature properly.

### ISSUE THREAD

**Issue by lianaoliveira** [chipsalliance/aib-phy-hardware#58]
AIB2.0 model does not support the receiver-domain transmit clock feature properly. Two fixes are needed to resolve the issue:
1.	In the aib_adapt_2doto.v file, assign the net fs_rcv_clk to m_fs_rcv_clk as follows:
assign m_fs_rcv_clk = fs_rcv_clk;

2.	In the aib_channel.v file, line 379, change the index of the iopad_aib array connected to iopad_rxclk net from 57 to 59, as follows:
.iopad_rxclk(iopad_aib[57]), //iopad_fs_rcv_clk),  --> current implementation
.iopad_rxclk(iopad_aib[59]), //iopad_fs_rcv_clk),  --> change needed

**Comment by xinyang2k** [comment]
Thanks for the good catch!
The issue was fixed and checked in.
