### ISSUE TITLE
AIB2.0 model connection mismatch

### ISSUE THREAD

**Issue by clesnps** [chipsalliance/aib-phy-hardware#60]
AIB2.0 model seems to have some connection mismatches, as follows :
1. In the /v2.0/rev1/rtl/aib_channel.v, line 182 to 186, pin AIB[71] is connected to 2 csrs :

          wire [39:0] csr_shift_rxdat = {AIB[100],AIB[101],AIB[98],AIB[99],AIB[96],AIB[97],AIB[94],AIB[95],AIB[92],AIB[93], 
                                         AIB[90], AIB[91], AIB[88],AIB[89],AIB[86],AIB[87],AIB[84],AIB[85],AIB[82],AIB[81],
                                         AIB[80], AIB[81], AIB[78],AIB[79],AIB[76],AIB[77],AIB[74],AIB[75],AIB[72],**AIB[71]**,
                                         AIB[68], AIB[69], AIB[66],AIB[67],AIB[64],AIB[65],AIB[62],AIB[63],AIB[60],AIB[61]};
          wire        csr_shift_fs_fwd_clk = **AIB[71]**;
          
2. The avmm address is the same for pin **we_tx_1** in /v2.0/rev1/rtl/aib_avmm_io_csr.v and pin **we_redund_3** /v2.0/rev1/rtl/aib_avmm_adapt_csr.v. Is this as expected ?

        wire	[3:0]  we_tx_1 = we & (addr[6:0] == 7'h1c) ? byteenable[3:0] : {4{1'b0}}; --> Line 54 in /v2.0/rev1/rtl/aib_avmm_adapt_csr.v
        wire	[3:0]  we_redund_3 = we & (addr[6:0] == 7'h1c) ? byteenable[3:0] : {4{1'b0}}; --> Line 54 in /v2.0/rev1/rtl/aib_avmm_io_csr.v

**Comment by xinyang2k** [comment]
Regarding 1. What you pointed out is true. **AIB[71]** is a typo. It should be AIB[73] instead for redundancy control enable.
Regarding 2. This is not a typo. Even though both are 7'h1c, we_tx_1 is 'h21C and we_redund_3 is 'h31C.

Thanks for pointing out the typo.  The correction has been checked in.
