### ISSUE TITLE
Gen2 Mode control in AIB2.0

### ISSUE THREAD

**Issue by clesnps** [chipsalliance/aib-phy-hardware#61]
I would like to confirm the function of signal m_gen2_mode in the v2.0 model since I cannot find it in the AIB 2.0 spec.  Does m_gen2_mode = 0 mean the model work in Gen1 mode in the spec and can compile with AIB 1.0 model? And m_gen2_mode = 1 means the model work in Gen2 mode in the spec and can compile with AIB 2.0 model?

**Comment by dkehlet** [comment]
Hi, please see page 33 in the 2.0 spec:
![image](https://user-images.githubusercontent.com/46331730/157895179-4d0fe897-5c8e-4948-b74b-2f4caf3e060c.png)

m_gen2_mode is only present in the AIB 2.0 model located here:
![image](https://user-images.githubusercontent.com/46331730/157895592-686d6931-055c-4384-9e8e-b7d297da500c.png)

**Comment by clesnps** [comment]
Hi @dkehlet, can you give me the link to the 2.0 spec referred to? I cannot find that signal in the spec here :
![image](https://user-images.githubusercontent.com/100890181/157999794-9d1e5a90-2a2a-44ce-8960-62f95e223408.png)

![image](https://user-images.githubusercontent.com/100890181/157999717-80c532bd-c298-4c6e-8ec3-71a5b4ea7b40.png)

**Comment by dkehlet** [comment]
Hi, the AIB specification was moved about 18 months ago to:
http://github.com/chipsalliance/AIB-specification 
Sorry about the old version under aib-phy-hardware/docs. I will delete it ASAP.

**Comment by clesnps** [comment]
Hi @dkehlet, thanks for your clarification.
So as my understanding, Gen1 mode of v2.0 model can compile with v1.0 model (AIB 1.0 spec), is that correct?

**Comment by dkehlet** [comment]
Hi @clesnps v2.0 model in Gen1 mode can simulate and operate in hardware with v1.0. Please see the README in this directory for the simulation example:
https://github.com/chipsalliance/aib-phy-hardware/tree/master/v2.0/rev1/dv/sims

**Comment by clesnps** [comment]
Thanks @dkehlet for your fast reply. It's clear for me now.
