### ISSUE TITLE
Repair of TX0 pin does not work v2.0/rev1/rtl/aib_ioring.v

### ISSUE THREAD

**Issue by tramphamsnps** [chipsalliance/aib-phy-hardware#68]
Hi,

When do repair from Tx0 to ns_rcv_clk, Tx0 is not shifted down to ns_rcv_clk.
I think the cause is from the connection of launch clock of io. It should be from tx_ilaunch_clk  instead of ns_rcv_clk_frmac

**The issue at v2.0/rev1/rtl/aib_ioring.v , line: 1119, 1120**
![image](https://user-images.githubusercontent.com/102977166/185857281-516d4804-8650-462f-9420-18db55714bb4.png)

**Recommend fixing at v2.0/rev1/rtl/aib_ioring.v , line: 1119, 1120**
![image](https://user-images.githubusercontent.com/102977166/185857470-759a1151-9b49-4d4a-923d-367c8ce9bc39.png)

This issue was reported at #44 , it is already fixed in v1.0/rev1/rtl/aib_ioring.v but it happens again in v2.0

Could you check this issue?

Thanks,

**Comment by dkehlet** [comment]
Hello, can you specify which RTL code you are referring to?
rev1? rev1.1?

**Comment by dkehlet** [comment]
Sorry, just saw the issue title (rev1).

**Comment by dkehlet** [comment]
Hello Tram,

Can you please try the v2.0/rev1.1 code? It is a separate implementation that is going in to silicon.

Meanwhile, if you wish to propose changes to rev1 to correct this and the other issue, please submit a pull request. We will review ASAP.

**Comment by tramphamsnps** [comment]
Hi Dkehlet,

Our scope is for rev1 only, we expect rev1 need to be updated.
Because I'm not familiar to github and the update is not much, please help to update rev1 based on the description "**Recommend fixing ...**"  in 1st comment of this issue report #68 and the issue report #69

Thanks,
Tram Pham
