### ISSUE TITLE
RX20 data is wrong when repair RX18,19 pins at v2.0/rev1/rtl/aib_channel.v

### ISSUE THREAD

**Issue by tramphamsnps** [chipsalliance/aib-phy-hardware#69]
Hi,

When do repair of Rx18/19, RX20 data is wrong because the repair shift is not correct.

**The issue at v2.0/rev1/rtl/aib_channel.v, line 183**
![image](https://user-images.githubusercontent.com/102977166/186061452-eea54046-801c-41fe-a88c-ee30a7ffbd33.png)
the yellow highlight should be AIB[83] (RX20) instead of AIB[81] (RX18).

**Recommend fixing at v2.0/rev1/rtl/aib_channel.v, line 183**
![image](https://user-images.githubusercontent.com/102977166/187219186-f076ef36-e465-418b-8877-45e34005fc0b.png)

Could you check this issue?

Thanks

**Comment by xinyang2k** [comment]
Thanks for point this out!

**Comment by dkehlet** [comment]
Thanks Julie!
