### ISSUE TITLE
Clarify file hierarchy and versions vs. spec revisions

### ISSUE THREAD

**Issue by CapucinedeBoissac** [chipsalliance/aib-phy-hardware#73]
Hello, 

Can you please clarify the relationships between the specification revisions and the AIB generations? 

- v1.0/rev1 contains the RTL describing the specs revision 1.2, i.e. the AIB Gen1 (Plus); but then why does how2use contain a simulation involving the phase compensation fifo, which is not supposed to be implemented in v1.0?
- V1.0/rev2 contains the RTL corresponding to the AIB Gen2; Then why is it the v1.0/rev1 code which was updated more recently?
- What are v2.0/rev1 and rev1.1?

Thanks in advance for your help

Capucine

**Comment by dkehlet** [comment]
Hello Capucine, 
_v1.0/rev1 contains the RTL describing the specs revision 1.2, i.e. the AIB Gen1 (Plus); but then why does how2use contain a simulation involving the phase compensation fifo, which is not supposed to be implemented in v1.0?_
The v1.0 code contains the FIFO which is not required by the AIB 1.x spec. It is extra functionality we provided. 

_V1.0/rev2 contains the RTL corresponding to the AIB Gen2; Then why is it the v1.0/rev1 code which was updated more recently?_
v1.0/rev1 had old files that were cleaned up. I recommend you to use v1.0/rev2 if you want to implement AIB 1.0 (spec revision 1.2).

_What are v2.0/rev1 and rev1.1?_
v2.0/rev1 is a behavioral model of AIB 2.0. rev1.1 is RTL extracted from an actual AIB 2.0 design. Functionally these are intended to be equivalent. rev1 simulates a lot faster than rev1.1, so for a lot of regressions people prefer to use rev1. For a tapeout, a user should run rev1.1 for final verification.

Dave

**Comment by CapucinedeBoissac** [comment]
Thank you Dave for your quick answer. Should I understand that the rev1.1 is a functional, synthesizable version of the AIB v2.0 interface? 

Capucine

**Comment by CapucinedeBoissac** [comment]
One more question: what are the main differences between v1.0 and v2.0? It seems that most of the upgrade resides in the lower I/O voltage, higher microbump density and the higher per-lane datarate, which I assume is enabled by the phase compensation FIFO. Since this functionality is extra in the V1.0/rev2, what do I earn by working with 2.0 RTL?

Thanks in advance

Capucine

**Comment by dkehlet** [comment]
_Should I understand that the rev1.1 is a functional, synthesizable version of the AIB v2.0 interface?_
For digital code, yes. But the analog cells are models. You need to create analog cells to have a working AIB 2.0 PHY. AIB 1.0 (v1.0) is similar in this respect.
See aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/

**Comment by dkehlet** [comment]
_what are the main differences between v1.0 and v2.0?
what do I earn by working with 2.0 RTL?_
From page 20 of https://github.com/chipsalliance/aib-phy-hardware/blob/master/docs/dkehlet_Chiplet_Technologies_Ecosystem_11_2020.pdf :
![image](https://user-images.githubusercontent.com/46331730/192563732-f0b27ff0-015f-4840-9067-abc2fa2fc255.png)

In short, AIB 2.0 gives 4x the bandwidth in the same die shoreline as AIB 1.0.
That said, if you want to interface with a Stratix 10 or Agilex FPGA (and you would need a sponsor and packaging agreement with Intel for this), then AIB 1.0 is sufficient.
