### ISSUE TITLE
unused port tclk_phy in v2.0/rev1

### ISSUE THREAD

**Issue by nij-intel** [chipsalliance/aib-phy-hardware#74]
Exists only in the model https://github.com/chipsalliance/aib-phy-hardware/blob/master/v2.0/rev1/rtl/aib_channel.v#L30 but not driven. Can this be removed?

**Comment by dkehlet** [comment]
Will fix if this file requires a critical update.

**Comment by xinyang2k** [comment]
This pin is not used currently. Ignore that for now.
