### ISSUE TITLE
AVMM register description not complete?

### ISSUE THREAD

**Issue by mhaedrich1** [chipsalliance/aib-phy-hardware#75]
In file _aib-phy-hardware/v2.0/rev1/dv/test/task/agent.sv_ in task _ms_phase_adjust_wrkarnd()_ and _sl_phase_adjust_wrkarnd()_ and in file _aib-phy-hardware/v2.0/rev1/dv/test/test_cases/reg_test.inc_ line 43 and 52 registers are read from and written to where I cannot find a description anywhere. I found files _aib-phy-hardware/docs/aib_csr_for_2_0_v5.xlsx_ and _aib-phy-hardware/docs/open_source_aib_csr.xlsx_ but there the registers / bits are described as reserved.
It is always for parts where MS_AIB_BCA or SL_AIB_BCA needs to be defined.

**Comment by dkehlet** [comment]
Hello, there is no plan for documenting these registers. If you have found a bug related to these registers affecting your simulations please file that as a separate issue.
